In [7]:
import pandas as pd 
import numpy as np
wine = pd.read_csv("D:\\Algorithms\\PCA DIMENSION REDUCTION\\wine.csv")

In [8]:
wine.describe()

Type     Alcohol       Malic         Ash  Alcalinity   Magnesium  \
count   0.0  178.000000  178.000000  178.000000  178.000000  178.000000   
mean    NaN    1.938202   13.000618    2.336348    2.366517   19.494944   
std     NaN    0.775035    0.811827    1.117146    0.274344    3.339564   
min     NaN    1.000000   11.030000    0.740000    1.360000   10.600000   
25%     NaN    1.000000   12.362500    1.602500    2.210000   17.200000   
50%     NaN    2.000000   13.050000    1.865000    2.360000   19.500000   
75%     NaN    3.000000   13.677500    3.082500    2.557500   21.500000   
max     NaN    3.000000   14.830000    5.800000    3.230000   30.000000   

          Phenols  Flavanoids  Nonflavanoids  Proanthocyanins       Color  \
count  178.000000  178.000000     178.000000       178.000000  178.000000   
mean    99.741573    2.295112       2.029270         0.361854    1.590899   
std     14.282484    0.625851       0.998859         0.124453    0.572359   
min     70.000000    0.980000       0.340000         0.130000    0.410000   
25%     88.000000    1.742500       1.205000         0.270000    1.250000   
50%     98.000000    2.355000       2.135000         0.340000    1.555000   
75%    107.000000    2.800000       2.875000         0.437500    1.950000   
max    162.000000    3.880000       5.080000         0.660000    3.580000   

              Hue    Dilution     Proline  Unnamed: 14  
count  178.000000  178.000000  178.000000   178.000000  
mean     5.058090    0.957449    2.611685   746.893258  
std      2.318286    0.228572    0.709990   314.907474  
min      1.280000    0.480000    1.270000   278.000000  
25%      3.220000    0.782500    1.937500   500.500000  
50%      4.690000    0.965000    2.780000   673.500000  
75%      6.200000    1.120000    3.170000   985.000000  
max     13.000000    1.710000    4.000000  1680.000000

In [9]:
wine.head()

Type  Alcohol  Malic   Ash  Alcalinity  Magnesium  Phenols  Flavanoids  \
0   NaN        1  14.23  1.71        2.43       15.6      127        2.80   
1   NaN        1  13.20  1.78        2.14       11.2      100        2.65   
2   NaN        1  13.16  2.36        2.67       18.6      101        2.80   
3   NaN        1  14.37  1.95        2.50       16.8      113        3.85   
4   NaN        1  13.24  2.59        2.87       21.0      118        2.80   

   Nonflavanoids  Proanthocyanins  Color   Hue  Dilution  Proline  Unnamed: 14  
0           3.06             0.28   2.29  5.64      1.04     3.92         1065  
1           2.76             0.26   1.28  4.38      1.05     3.40         1050  
2           3.24             0.30   2.81  5.68      1.03     3.17         1185  
3           3.49             0.24   2.18  7.80      0.86     3.45         1480  
4           2.69             0.39   1.82  4.32      1.04     2.93          735

In [10]:
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
from sklearn.preprocessing import scale

In [11]:
wine=wine.iloc[:,1:]
wine.head()

Alcohol  Malic   Ash  Alcalinity  Magnesium  Phenols  Flavanoids  \
0        1  14.23  1.71        2.43       15.6      127        2.80   
1        1  13.20  1.78        2.14       11.2      100        2.65   
2        1  13.16  2.36        2.67       18.6      101        2.80   
3        1  14.37  1.95        2.50       16.8      113        3.85   
4        1  13.24  2.59        2.87       21.0      118        2.80   

   Nonflavanoids  Proanthocyanins  Color   Hue  Dilution  Proline  Unnamed: 14  
0           3.06             0.28   2.29  5.64      1.04     3.92         1065  
1           2.76             0.26   1.28  4.38      1.05     3.40         1050  
2           3.24             0.30   2.81  5.68      1.03     3.17         1185  
3           3.49             0.24   2.18  7.80      0.86     3.45         1480  
4           2.69             0.39   1.82  4.32      1.04     2.93          735

In [12]:
wine_normal=scale(wine)

In [14]:
wine_normal

array([[-1.21394365,  1.51861254, -0.5622498 , ...,  0.36217728,
         1.84791957,  1.01300893],
       [-1.21394365,  0.24628963, -0.49941338, ...,  0.40605066,
         1.1134493 ,  0.96524152],
       [-1.21394365,  0.19687903,  0.02123125, ...,  0.31830389,
         0.78858745,  1.39514818],
       ...,
       [ 1.37386437,  0.33275817,  1.74474449, ..., -1.61212515,
        -1.48544548,  0.28057537],
       [ 1.37386437,  0.20923168,  0.22769377, ..., -1.56825176,
        -1.40069891,  0.29649784],
       [ 1.37386437,  1.39508604,  1.58316512, ..., -1.52437837,
        -1.42894777, -0.59516041]])

In [15]:
pca=PCA(n_components=13)

In [16]:
pca_values=pca.fit_transform(wine_normal)

In [17]:
pca_values[0]

array([-3.5229339 , -1.45309844, -0.16479549, -0.01327282,  0.73734536,
       -0.30071618,  0.57387557,  0.05563728, -0.45876506,  1.06556955,
       -0.4204939 ,  0.55292777, -0.30297818])

In [18]:
# The amount of variance that each PCA explains is 
var=pca.explained_variance_ratio_

In [19]:
var

array([0.39542486, 0.17836259, 0.10329102, 0.06627984, 0.06267875,
       0.0480556 , 0.03955707, 0.02500244, 0.02103871, 0.01873615,
       0.01613203, 0.01205691, 0.00925458])

In [20]:
# Cumulative variance
var1 = np.cumsum(np.round(var,decimals = 4)*100)
var1

array([39.54, 57.38, 67.71, 74.34, 80.61, 85.42, 89.38, 91.88, 93.98,
       95.85, 97.46, 98.67, 99.6 ])

In [21]:
################## Clustering  ##########################
new_df = pd.DataFrame(pca_values[:,0:4])
new_df.head()

0         1         2         3
0 -3.522934 -1.453098 -0.164795 -0.013273
1 -2.528858  0.330019 -2.026707 -0.417144
2 -2.785029 -1.036936  0.983238  0.664232
3 -3.922588 -2.768210 -0.174968  0.565088
4 -1.407511 -0.867773  2.025829 -0.440906

In [22]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters = 3)

In [23]:
kmeans.fit(new_df)

C:\Users\Anand Huded\AppData\Roaming\Python\Python39\site-packages\sklearn\cluster\_kmeans.py:1334: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


KMeans(n_clusters=3)

In [24]:
kmeans.labels_

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])